"""Canonical MCP tool parameter types and metadata.

The **authoritative** MCP wire schemas are generated by the SDK from the tool
handler signatures in :mod:`qwen_research.mcp.server` (via pydantic). There are
no hand-written JSON-Schema dicts here that could drift from the code: the
parameter *types* used in those signatures are defined once, below, as
``Annotated``/``Literal`` aliases, and the SDK turns them into the wire schema
(``Literal`` → ``enum``, ``Field(description=...)`` → ``description``, the
signature default → ``default``, absence of a default → ``required``).

Tool descriptions and the tool list also live here, because they are the same
metadata the SDK exposes on the wire via ``add_tool(description=...)``.
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

# Enum value sets. These enumerate the domain enum values / profile names as
# string ``Literal``s (so the wire schema carries a simple inline ``enum`` and
# handlers receive plain strings). The values are the *same* values the domain
# enumerates; the tests in ``tests/mcp/test_schemas.py`` assert the resulting
# wire enums match ``OperatingMode`` and ``PROFILES`` exactly, so they cannot
# drift silently.
OperatingModeName = Literal["studio_native", "gateway_inference", "hybrid"]
ReasoningProfileName = Literal["FAST", "NORMAL", "DEEP", "XHIGH", "EXTREME"]

# Parameter types (Annotated[..., Field(description=...)]). Defaults and
# required-ness are declared in the handler signatures, not here.
SessionIdParam = Annotated[str, Field(description="The session identifier.")]
TaskIdParam = Annotated[str, Field(description="The task identifier.")]
DescriptionParam = Annotated[str, Field(description="The task description.")]
ProjectIdParam = Annotated[str, Field(description="The project id for the session.")]
ModeParam = Annotated[OperatingModeName, Field(description="The operating mode.")]
ReasoningProfileParam = Annotated[
    ReasoningProfileName, Field(description="The reasoning profile name.")
]
MetadataParam = Annotated[
    dict[str, str] | None, Field(description="Optional string key/value metadata.")
]
OptionalSessionIdParam = Annotated[
    str | None,
    Field(description="Optional existing session id; a new session is created if omitted."),
]
QueryParam = Annotated[str, Field(description="The search query text.")]
LimitParam = Annotated[int, Field(description="Maximum number of results.", ge=1, le=100)]
RootsParam = Annotated[
    list[str] | None, Field(description="Optional corpus root ids to restrict the search to.")
]
DocumentTypesParam = Annotated[
    list[str] | None,
    Field(description="Optional media types (e.g. 'text/markdown') to filter by."),
]
PathPrefixParam = Annotated[
    str | None, Field(description="Optional relative path prefix to filter by.")
]
DocumentIdParam = Annotated[str, Field(description="The document identifier.")]

TOOL_DESCRIPTIONS: dict[str, str] = {
    "get_session": "Return a session by its session id.",
    "create_session": (
        "Create a new research session. Optionally specify a project id and "
        "operating mode; defaults to project 'default' and mode 'studio_native'."
    ),
    "execute_task": (
        "Create, classify, and plan a research task, optionally within an "
        "existing session and under a named reasoning profile."
    ),
    "continue_task": "Advance a task one step along its execution progression.",
    "get_task_state": "Return the current state of a task.",
    "get_research_state": "Return the structured research state of a task.",
    "search_corpus": (
        "Search the local corpus for text relevant to a query and return ranked "
        "evidence with source provenance (file, page/section, score, excerpt)."
    ),
    "get_source": "Return metadata and structure for a document by its id.",
}

#: The Phase 2 minimal tool set, in registration order.
DEFAULT_TOOLS: tuple[str, ...] = (
    "get_session",
    "create_session",
    "execute_task",
    "continue_task",
    "get_task_state",
    "get_research_state",
    "search_corpus",
    "get_source",
)
