"""Canonical MCP tool parameter types and metadata.

The **authoritative** MCP wire schemas are generated by the SDK from the tool
handler signatures in :mod:`qwen_research.mcp.server` (via pydantic). There are
no hand-written JSON-Schema dicts here that could drift from the code: the
parameter *types* used in those signatures are defined once, below, as
``Annotated``/``Literal`` aliases, and the SDK turns them into the wire schema
(``Literal`` → ``enum``, ``Field(description=...)`` → ``description``, the
signature default → ``default``, absence of a default → ``required``).

Tool descriptions and the tool list also live here, because they are the same
metadata the SDK exposes on the wire via ``add_tool(description=...)``.
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

# Enum value sets. These enumerate the domain enum values / profile names as
# string ``Literal``s (so the wire schema carries a simple inline ``enum`` and
# handlers receive plain strings). The values are the *same* values the domain
# enumerates; the tests in ``tests/mcp/test_schemas.py`` assert the resulting
# wire enums match ``OperatingMode`` and ``PROFILES`` exactly, so they cannot
# drift silently.
OperatingModeName = Literal["studio_native", "gateway_inference", "hybrid"]
ReasoningProfileName = Literal["FAST", "NORMAL", "DEEP", "XHIGH", "EXTREME"]

# Parameter types (Annotated[..., Field(description=...)]). Defaults and
# required-ness are declared in the handler signatures, not here.
SessionIdParam = Annotated[str, Field(description="The session identifier.")]
TaskIdParam = Annotated[str, Field(description="The task identifier.")]
DescriptionParam = Annotated[str, Field(description="The task description.")]
ProjectIdParam = Annotated[str, Field(description="The project id for the session.")]
ModeParam = Annotated[OperatingModeName, Field(description="The operating mode.")]
ReasoningProfileParam = Annotated[
    ReasoningProfileName, Field(description="The reasoning profile name.")
]
MetadataParam = Annotated[
    dict[str, str] | None, Field(description="Optional string key/value metadata.")
]
OptionalSessionIdParam = Annotated[
    str | None,
    Field(description="Optional existing session id; a new session is created if omitted."),
]
QueryParam = Annotated[str, Field(description="The search query text.")]
LimitParam = Annotated[int, Field(description="Maximum number of results.", ge=1, le=100)]
RootsParam = Annotated[
    list[str] | None, Field(description="Optional corpus root ids to restrict the search to.")
]
DocumentTypesParam = Annotated[
    list[str] | None,
    Field(description="Optional media types (e.g. 'text/markdown') to filter by."),
]
PathPrefixParam = Annotated[
    str | None, Field(description="Optional relative path prefix to filter by.")
]
DocumentIdParam = Annotated[str, Field(description="The document identifier.")]

# Phase 4 retrieval params.
RetrievalModeName = Literal["lexical", "semantic", "hybrid"]
RetrievalModeParam = Annotated[RetrievalModeName, Field(description="Retrieval mode.")]
LexicalKParam = Annotated[int, Field(description="Lexical candidate count.", ge=1, le=100)]
SemanticKParam = Annotated[int, Field(description="Semantic candidate count.", ge=1, le=100)]
MaxChunksPerDocumentParam = Annotated[
    int, Field(description="Maximum chunks per document (diversity).", ge=1, le=50)
]

# Phase 4 memory params.
OptionalQueryParam = Annotated[str | None, Field(description="Optional query text.")]
ContentParam = Annotated[str, Field(description="The memory content (structured text).")]
StringListParam = Annotated[
    list[str] | None, Field(description="Optional list of reference ids.")
]
StatusParam = Annotated[str | None, Field(description="Optional status value.")]

# Phase 5 evidence-integrity params.
ClaimTypeName = Literal[
    "factual", "causal", "comparative", "quantitative", "definitional",
    "predictive", "methodological", "normative", "unknown",
]
ClaimTypeParam = Annotated[ClaimTypeName, Field(description="The claim type.")]
ClaimIdParam = Annotated[str, Field(description="The claim identifier.")]
EvidenceIdParam = Annotated[str, Field(description="The evidence (chunk) identifier.")]
ReportIdParam = Annotated[str, Field(description="The verification report identifier.")]
ClaimEvidenceRelationshipName = Literal[
    "supports", "contradicts", "qualifies", "contextualizes", "does_not_address",
]
ClaimEvidenceRelationshipParam = Annotated[
    ClaimEvidenceRelationshipName, Field(description="The claim-evidence relationship.")
]
RationaleParam = Annotated[str | None, Field(description="Optional rationale text.")]

TOOL_DESCRIPTIONS: dict[str, str] = {
    "get_session": "Return a session by its session id.",
    "create_session": (
        "Create a new research session. Optionally specify a project id and "
        "operating mode; defaults to project 'default' and mode 'studio_native'."
    ),
    "execute_task": (
        "Create, classify, and plan a research task, optionally within an "
        "existing session and under a named reasoning profile."
    ),
    "continue_task": "Advance a task one step along its execution progression.",
    "get_task_state": "Return the current state of a task.",
    "get_research_state": "Return the structured research state of a task.",
    "search_corpus": (
        "Search the local corpus for text relevant to a query and return ranked "
        "evidence with source provenance (file, page/section, score, excerpt)."
    ),
    "get_source": "Return metadata and structure for a document by its id.",
    "get_project_memory": "Return project-scoped memory (goals, scope, sources, notes).",
    "get_research_memory": "Return research-derived memory (claims/conclusions) with provenance.",
    "get_open_questions": "Return unresolved research questions for a project.",
    "save_research_memory": "Save research-derived memory with explicit provenance.",
    "create_claim": "Create a structured claim (status UNREVIEWED; no truth assertion).",
    "link_claim_evidence": (
        "Link a project-scoped claim to corpus evidence with an explicit relationship."
    ),
    "assess_evidence": "Produce a structured assessment of evidence against a claim.",
    "verify_claim": "Run the deterministic verification pipeline for a project-scoped claim.",
    "get_verification_report": "Return a persisted verification report (project-scoped) by id.",
    "get_contradictions": "Return contradictions (candidates/confirmed) for a project.",
}

#: The Phase 2 minimal tool set, in registration order.
DEFAULT_TOOLS: tuple[str, ...] = (
    "get_session",
    "create_session",
    "execute_task",
    "continue_task",
    "get_task_state",
    "get_research_state",
    "search_corpus",
    "get_source",
    "get_project_memory",
    "get_research_memory",
    "get_open_questions",
    "save_research_memory",
    "create_claim",
    "link_claim_evidence",
    "assess_evidence",
    "verify_claim",
    "get_verification_report",
    "get_contradictions",
)
